targets:
  $default:
    builders:
      neat_builder:
        enabled: true
        
builders:
  neat_builder:
    import: "package:neat/neat_generator/neat_generator.dart"
    builder_factories: ["neatGenerator"]
    build_extensions: {".dart": [".nt.dart"]}
    auto_apply: dependents
    build_to: source
