name: neat
description: "A collection of utility functions and code generators that helps making neat flutter code"
version: 0.0.2
repository: https://github.com/Pierre2tm/neat

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^2.7.0
  build: ^2.1.0
  build_config: ^1.0.0
  code_builder: ^4.1.0
  collection: ^1.15.0
  dart_style: ^2.0.3
  source_gen: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2  

flutter: