name: neat_annotations
description: "Neat's code generator's annotations"
version: 0.1.1
homepage: https://github.com/Pierre2tm/neat
repository: https://github.com/Pierre2tm/neat

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1