name: neat_annotations
description: "Neat's code generator's annotations"
version: 0.1.0
homepage: https://github.com/Pierre2tm/neat
repository: https://github.com/Pierre2tm/neat

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0